// This file was generated by resman.py on 2026-10-09 at 20:22:28

#pragma once

#include <stdint.h>

typedef struct {
    const int8_t *data;
    uint32_t length;
    uint32_t rate;
    uint8_t loop;
} tpaAudioSample;

extern const tpaAudioSample tpaAudioSamples[];
extern const uint32_t tpaAudioSampleCount;
